### PR TITLE
Add Shelly Blu Gateway model

### PR DESCRIPTION
**Pull request by chemelli74**

### CODE REVIEW

**Review by bieniu — APPROVED** [review]
Looks good 👍

**Review by thecode — COMMENTED** [review]
Until now we added devices while keeping the models with lexicographical sort, please fix this in a new PR. Thanks

**Comment by bieniu** [comment]
I'm working on the change related on model consts.

**Comment by chemelli74** [comment]
> Until now we added devices while keeping the models with lexicographical sort, please fix this in a new PR. Thanks

We are thinking to sort by description and not by model.

**Comment by thecode** [comment]
> > Until now we added devices while keeping the models with lexicographical sort, please fix this in a new PR. Thanks
> 
> We are thinking to sort by description and not by model.

When you do that sort all of them, for now it is is sorted by model. We should keep this consistent until this is changed!

**Comment by bieniu** [comment]
https://github.com/home-assistant-libs/aioshelly/pull/449

**Pull request merged**
