### PR TITLE
Add Shelly DALI Dimmer Gen3

### PR DESCRIPTION
**Pull request by michalmo**
Adding this new device:
https://www.shelly.com/products/shelly-dali-dimmer-gen3
https://shelly-api-docs.shelly.cloud/gen2/Devices/Gen3/ShellyDDimmerG3
image

### CODE REVIEW

**Comment by bieniu** [comment]
Could you post responses to:
- /shelly
- /rpc/Shelly.GetConfig
- /rpc/Shelly.GetStatus

**Comment by michalmo** [comment]
Sure, here are the responses with some addresses redacted.

BTW, the device is working fine without these changes (just not showing a pretty model name). I think it's entirely compatible with the Shelly Dimmer 0/1-10V PM Gen3.

* /shelly
```
{
    "app": "DDimmerG3",
    "auth_domain": "shellyddimmerg3-XXXXXXXXXXXX",
    "auth_en": true,
    "fw_id": "20240813-103033/1.4.99-ddimmerg3prod0-gac15c83",
    "gen": 3,
    "id": "shellyddimmerg3-XXXXXXXXXXXX",
    "mac": "XXXXXXXXXXXX",
    "model": "S3DM-0A1WW",
    "name": null,
    "slot": 1,
    "ver": "1.4.99-ddimmerg3prod0"
}
```
* /rpc/Shelly.GetConfig
```
{
    "ble": {
        "enable": true,
        "observer": {
            "enable": false
        },
        "rpc": {
            "enable": true
        }
    },
    "bthome": {},
    "cloud": {
        "enable": false,
        "server": "iot.shelly.cloud:6012/jrpc"
    },
    "dali": {},
    "input:0": {
        "enable": true,
        "factory_reset": false,
        "id": 0,
        "invert": false,
        "name": null,
        "type": "button"
    },
    "input:1": {
        "enable": true,
        "factory_reset": false,
        "id": 1,
        "invert": false,
        "name": null,
        "type": "button"
    },
    "knx": {
        "enable": false,
        "ia": "15.15.255",
        "routing": {
            "addr": "224.0.23.12:3671"
        }
    },
    "light:0": {
        "auto_off": false,
        "auto_off_delay": 60.0,
        "auto_on": false,
        "auto_on_delay": 60.0,
        "button_fade_rate": 5,
        "button_presets": {
            "button_doublepush": {
                "brightness": 100
            }
        },
        "id": 0,
        "in_mode": "dim",
        "initial_state": "restore_last",
        "min_brightness_on_toggle": 3,
        "name": null,
        "night_mode": {
            "active_between": [],
            "brightness": 50,
            "enable": false
        }
    },
    "mqtt": {
        "client_id": "shellyddimmerg3-XXXXXXXXXXXX",
        "enable": false,
        "enable_control": true,
        "enable_rpc": true,
        "rpc_ntf": true,
        "server": null,
        "ssl_ca": null,
        "status_ntf": false,
        "topic_prefix": "shellyddimmerg3-XXXXXXXXXXXX",
        "use_client_cert": false,
        "user": null
    },
    "sys": {
        "cfg_rev": 12,
        "debug": {
            "file_level": null,
            "level": 2,
            "mqtt": {
                "enable": false
            },
            "udp": {
                "addr": null
            },
            "websocket": {
                "enable": false
            }
        },
        "device": {
            "addon_type": null,
            "discoverable": true,
            "fw_id": "20240813-103033/1.4.99-ddimmerg3prod0-gac15c83",
            "mac": "XXXXXXXXXXXX",
            "name": null
        },
        "location": {
            "lat": 12.3456,
            "lon": 12.3456,
            "tz": "XXXXXX/XXXXXX"
        },
        "rpc_udp": {
            "dst_addr": null,
            "listen_port": null
        },
        "sntp": {
            "server": "time.google.com"
        },
        "ui_data": {}
    },
    "wifi": {
        "ap": {
            "enable": false,
            "is_open": true,
            "range_extender": {
                "enable": false
            },
            "ssid": "ShellyDDimmerG3-XXXXXXXXXXXX"
        },
        "roam": {
            "interval": 60,
            "rssi_thr": -80
        },
        "sta": {
            "enable": true,
            "gw": "XXX.XXX.XXX.XXX",
            "ip": "XXX.XXX.XXX.XXX",
            "ipv4mode": "static",
            "is_open": false,
            "nameserver": "XXX.XXX.XXX.XXX",
            "netmask": "XXX.XXX.XXX.XXX",
            "ssid": "XXXXXXXXXX"
        },
        "sta1": {
            "enable": false,
            "gw": null,
            "ip": null,
            "ipv4mode": "dhcp",
            "is_open": true,
            "nameserver": null,
            "netmask": null,
            "ssid": null
        }
    },
    "ws": {
        "enable": false,
        "server": null,
        "ssl_ca": "ca.pem"
    }
}
```
* /rpc/Shelly.GetStatus
```
{
    "ble": {},
    "bthome": {
        "errors": [
            "observer_disabled"
        ]
    },
    "cloud": {
        "connected": false
    },
    "dali": {
        "cg_count": 0
    },
    "input:0": {
        "id": 0,
        "state": null
    },
    "input:1": {
        "id": 1,
        "state": null
    },
    "knx": {},
    "light:0": {
        "brightness": 100,
        "id": 0,
        "output": false,
        "source": "dim",
        "temperature": {
            "tC": 55.7,
            "tF": 132.2
        }
    },
    "mqtt": {
        "connected": false
    },
    "sys": {
        "available_updates": {},
        "cfg_rev": 12,
        "fs_free": 581632,
        "fs_size": 1048576,
        "kvs_rev": 0,
        "mac": "XXXXXXXXXXXX",
        "ram_free": 94988,
        "ram_size": 261312,
        "reset_reason": 1,
        "restart_required": false,
        "schedule_rev": 0,
        "time": "17:12",
        "unixtime": 1730650342,
        "uptime": 16408,
        "webhook_rev": 0
    },
    "wifi": {
        "rssi": -65,
        "ssid": "XXXXXXXXXX",
        "sta_ip": "XXX.XXX.XXX.XXX",
        "status": "got ip"
    },
    "ws": {
        "connected": false
    }
}
```

**Comment by bieniu** [comment]
Thanks @michalmo I was worried that the integration would require changes to support this model, but everything looks good and you've confirmed that the device works.

**Review by bieniu — APPROVED** [review]
Thanks @michalmo

**Pull request merged**
