### PR TITLE
Add supported devices list

### PR DESCRIPTION
**Pull request by Misiu**
based on https://github.com/home-assistant-libs/aioshelly/blob/main/aioshelly/__init__.py#L8-L17

### CODE REVIEW

**Comment by balloob** [comment]
Those are not supported, those are just ones that we have human readable names for.

**Comment by balloob** [comment]
Every Shelly device is supported. We can read their info and blocks and allow `set_state`.

**Comment by Misiu** [comment]
@balloob if every Shelly device is supported I can extend the list.
What about roller shutter mode for Shelly 2.5?
Should I ask for support here or in HA repo?
This mode is most useful for me.

**Comment by balloob** [comment]
This wrapper shows the data from the API and that's it. It doesn't care if something is in roller mode or not. That's up to the something that uses this lib to implement. So not this repo.

Also no feature requests in the core repo but on the forums 👍

**Comment by Misiu** [comment]
@balloob thanks for the reeply.
I'll create FR on the forum and will test new integration with devices I have.

**Pull request merged**
