### PR TITLE
Bump version to 8.0.2

### PR DESCRIPTION
**Pull request by thecode**
Release mainly to have https://github.com/home-assistant-libs/aioshelly/pull/501 in beta

### CODE REVIEW

**Review by bieniu — APPROVED** [review]

**Comment by chemelli74** [comment]
Can we kindly wit for a couple of PRs that are ready please ?

**Comment by bieniu** [comment]
Simone, I think we can't say about any of the open PRs that it is ready.
If we manage to finish any, we can release the next version of aioshelly.

**Comment by thecode** [comment]
> Can we kindly wit for a couple of PRs that are ready please ?

Ok, we wait can wait with it until Tuesday (Wednesday - beta day, I am OOO), I will prepare the corresponding core PR as draft so we are ready.

**Review by chemelli74 — APPROVED** [review]
As per discord chat, please proceed with release

**Pull request merged**
