### PR TITLE
Add debug logging

### PR DESCRIPTION
**Pull request by thecode**
To help debug https://github.com/home-assistant/core/issues/116975 better

### CODE REVIEW

**Comment by chemelli74** [comment]
What about adding also the MAC address to the log message ?
Just in case there is also DHCP kicking in between one log session and the next one

**Comment by thecode** [comment]
> What about adding also the MAC address to the log message ? Just in case there is also DHCP kicking in between one log session and the next one

Added to device create:
```
DEBUG:aioshelly.block_device.device:host 192.168.1.135: block device create, MAC: CAAB12345ABC
DEBUG:aioshelly.rpc_device.device:host 192.168.1.35:80: RPC device create, MAC: 12345AB50124

```

**Review by bieniu — APPROVED** [review]

**Review by chemelli74 — APPROVED** [review]
Thx!

**Comment by thecode** [comment]
Thanks!

**Pull request merged**
